# Generated by Django 2.2.2 on 2019-06-10 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0002_auto_20190610_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
