# Generated by Django 2.2.2 on 2019-06-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0003_auto_20190610_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='city',
            field=models.CharField(default='Surat', max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='patient',
            name='state',
            field=models.CharField(default='Gujarat', max_length=50),
        ),
    ]
