# Generated by Django 2.2.2 on 2019-06-13 06:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0004_auto_20190613_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
    ]
