# Generated by Django 2.2.2 on 2019-06-13 12:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0005_remove_patient_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dob',
            field=models.DateField(),
        ),
    ]
