# Generated by Django 2.2.2 on 2019-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('mainapp', '0006_auto_20190613_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
